  
# 核心任务
- name: ORACLEDATABASE
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
    
  pre_tasks:  
    - git:
       repo: "https://github.com/Websoft9/role_oracledb"
       dest: "/data/ansible-oracle"
       version: dev

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_cloud, tags: "role_cloud"} 
    - {role: role_jdk, tags: "role_jdk"} 
