- src: http://github.com/websoft9dev/role_common

- src: http://github.com/websoft9dev/role_oracle

- src: http://github.com/websoft9dev/role_jdk

- src: http://github.com/websoft9dev/role_preend

- src: http://github.com/websoft9dev/role_end
